### ISSUE TITLE
What is the best way to update `apicurio-registry`?

### ISSUE THREAD

**Issue by LittleWat** [Apicurio/apicurio-registry-examples#40]
Hello! Thank you for creating nice samples!

We updated the apicurio-registry from `2.3.1.Final` to `2.4.1.Final`

However, my client app based on [the sample app](https://github.com/Apicurio/apicurio-registry-examples/tree/main/simple-avro-maven) got the following error:

```log
simple-avro-maven-producer Starting example SimpleAvroMavenExample
simple-avro-maven-producer SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
simple-avro-maven-producer SLF4J: Defaulting to no-operation (NOP) logger implementation
simple-avro-maven-producer SLF4J: See <a target="_blank" data-stringify-link="http://www.slf4j.org/codes.html#StaticLoggerBinder" delay="150" data-sk="tooltip_parent" href="http://www.slf4j.org/codes.html#StaticLoggerBinder" rel="noopener noreferrer" tabindex="-1" data-remove-tab-index="true">http://www.slf4j.org/codes.html#StaticLoggerBinder</a> for further details.
simple-avro-maven-producer Type is PRODUCER
simple-avro-maven-producer Start producing messages.
simple-avro-maven-producer Closing the producer.
simple-avro-maven-producer Exception in thread "main" java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2023-01-20T07:14:31Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"
simple-avro-maven-producer  at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 47] (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])
simple-avro-maven-producer     at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:60)
simple-avro-maven-producer     at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:204)
simple-avro-maven-producer     at io.apicurio.registry.rest.client.impl.RegistryClientImpl.createArtifact(RegistryClientImpl.java:263)
simple-avro-maven-producer     at io.apicurio.registry.rest.client.RegistryClient.createArtifact(RegistryClient.java:134)
simple-avro-maven-producer     at io.apicurio.registry.resolver.DefaultSchemaResolver.lambda$handleAutoCreateArtifact$2(DefaultSchemaResolver.java:236)
simple-avro-maven-producer     at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:142)
simple-avro-maven-producer     at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:181)
simple-avro-maven-producer     at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:141)
simple-avro-maven-producer     at io.apicurio.registry.resolver.ERCache.getByContent(ERCache.java:121)
simple-avro-maven-producer     at io.apicurio.registry.resolver.DefaultSchemaResolver.handleAutoCreateArtifact(DefaultSchemaResolver.java:234)
simple-avro-maven-producer     at io.apicurio.registry.resolver.DefaultSchemaResolver.getSchemaFromRegistry(DefaultSchemaResolver.java:115)
simple-avro-maven-producer     at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchema(DefaultSchemaResolver.java:88)
simple-avro-maven-producer     at io.apicurio.registry.serde.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:83)
simple-avro-maven-producer     at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:929)
simple-avro-maven-producer     at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:889)
simple-avro-maven-producer     at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:775)
simple-avro-maven-producer     at io.apicurio.registry.examples.simple.avro.maven.SimpleAvroMavenExample.keepPublishing(SimpleAvroMavenExample.java:150)
simple-avro-maven-producer     at io.apicurio.registry.examples.simple.avro.maven.SimpleAvroMavenExample.main(SimpleAvroMavenExample.java:111)
simple-avro-maven-producer Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2023-01-20T07:14:31Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"
simple-avro-maven-producer  at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 47] (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])
simple-avro-maven-producer     at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1991)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1219)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:195)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:303)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:281)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
simple-avro-maven-producer     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
simple-avro-maven-producer     at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:56)
simple-avro-maven-producer     ... 17 more
Stream closed EOF for kafka-apicurio-sample/simple-avro-maven-producer-86b8f7f96-fzhrf (simple-avro-maven-produce
```

This was fixed by updating the following client library version to `2.4.1.Final`.
https://github.com/Apicurio/apicurio-registry-examples/blob/544bb0f58323090bd9b38e032b8b6977c31ead72/pom.xml#L77-L78

From this experience, we cannot update the `apicurio registry`  without thinking the clients.

I confirmed that the `2.4.1.Final` client library worked well with the `2.3.1.Final` apicurio registry.

Is this intentional? I mean,  is it recommended to update the client library first?

**Comment by EricWittmann** [comment]
Ah this is an unfortunate situation where the server was incorrectly encoding the data-time fields in API responses.  We fixed that bug but it does mean that old clients will no longer work with the latest server.

In this case, the correct approach is to upgrade the clients to the latest version (they client knows how to handle both formats) and **then** upgrade the server.

Sorry for the inconvenience.  This should be a very uncommon occurrence (this type of breakage).  In the normal upgrade process (except for major version changes) it shouldn't matter what order you choose to upgrade.

**Comment by LittleWat** [comment]
I got it, thank you for your reply!
I hope this would be a very uncommon occurrence ^^;

**Comment by LittleWat** [comment]
@EricWittmann Sorry for asking again 🙇 

Can we get this kind of info in [the release notes](https://github.com/Apicurio/apicurio-registry/releases) or something else in the future? 

These info will be quite useful for preparing the Apicurio upgrades.

**Comment by EricWittmann** [comment]
Yes we always do our best to include information like that in the release notes - but we missed it this time.  It was a lesson learned.

**Comment by LittleWat** [comment]
Understood. Thank you!!
